---
trigger: initiative
title: Initiative Report
description: Howie Initiative Progress Report
surfaces:
  - issue
steps:
  - type: form
    style: embedded
    actions:
      submit: Submit
    body:
      - type: dropdown
        attributes:
          id: trending
          label: Trending
          options:
            - label: "🟢 on track"
              value: "🟢 on track"
            - label: "🟡 at risk"
              value: "🟡 at risk"
            - label: "🔴 high risk"
              value: "🔴 high risk"
            - label: "⚪ inactive"
              value: "⚪ inactive"
            - label: "🟣 done"
              value: "🟣 done"
      - type: input
        attributes:
          id: target_date
          label: Target date
          format: date
      - type: textarea
        attributes:
          id: update
          label: Update
          placeholder: A few words on how it's going
      - type: markdown
        attributes:
          id: deprecation
          value: "📌 This slash command is being replaced in the near future by the `/report` command. Read more [here](https://github.com/orgs/github/teams/howie-engineering/posts/5) to update your `.github/hww.yml` configuration."
  - type: fill
    submit_form: true
    template_path: .github/commands/howie-initiative-report.liquid
