#!/usr/bin/env bash
#
# This script is run automatically, early, in Janky CI builds.
# It saves the authentication token in the repository so that
# it's part of the Docker context and thus available to Make.
set -euo pipefail

if [[ -n "${CODESPACES:-}" && "$CODESPACES" = "true" ]]; then
    echo "❌ This script should only be run by Janky, and not in a Codespace. Try using './kupl bootstrap' to install dependencies."
    exit 1
fi

echo "Saving goproxy authentication token." >&2
echo "$BP_GITHUB_TOKEN" > .goproxytoken
