apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: actions-example-go
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: actions-example-go
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
  minReplicas: 10
  maxReplicas: 30
