# This is a SecretProviderClass example using aad-pod-identity to access the key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: example-go-kv
  namespace: actions-example-go
spec:
  provider: azure
  parameters:
    useVMManagedIdentity: "true"                                   # true for using managed identity
    userAssignedIdentityID: 52e156f1-de34-437e-8c7a-bb41ff6f9660   # The clientID of the user-assigned managed identity for the kupl eus cluster
    keyvaultName: kupl-secrets-go
    tenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47
    objects:  |
      array:
        - |
          objectName: ExampleSecret
          objectType: secret             # object types: secret, key, or cert
          objectVersion: ""              # [OPTIONAL] object versions, default to latest if empty
