apiVersion: v1
kind: Service
metadata:
  name: actions-example-go
spec:
  type: ClusterIP
  selector:
    app: actions-example-go
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
